# Introduccion a Numpy

[Numpy](https://numpy.org/doc/stable/#) Es un biblioteca fundamental para la computacion cientifica en Python.
* Proporciona arrays N-dimensionales
* Implementa funciones matematicas sofisticadas
* Proporciona herramientas para integrar c/c++ y Forton
* Proporciona mecanismos para facilitar la realizacion de tareas relacionadas con con el algebra lineal o numeros aleatorios

## Imports

In [1]:
import numpy as np

### Arrays
Un **Array** es una estructura de datos que consiste en una seleccion de elementos (Valores o variables) cada uno identificado por al menos un indice o clave, Un array se almacena de modo de la posicion de cada elemento de puede calcular a partir de su tupla de indice mediante una formula matematica. el tipo mas simple de array es un array lineal tambien llamado array unidimensional.

### En Numpy:
* Cada dimension se denomina **axis**.
* En numero de dimensiones se denomina **rank**
* La lista de dimensiones con su correspondiente longitud se denomina **shape**
* El número total de elementos (multiplicacion de la longitud de las dimensiones) se denomina **size**.

In [2]:
# Array cuyos valores son todos ceros.
a = np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

_**a**_ es un array:
* Con dos **axis**, el primero de longitud 2 y el segundo de longitud 4.
* Con un **rank** igual al 2
* Con un **shape** que es igual a (2 . 4)
* Con un **size** igual a 8

In [3]:
a.shape

(2, 4)

## Creación de arrays 

In [4]:
# Array cuyos valores son todos 0.
np.zeros((2, 3, 4))
 #Array cuyos valores son todos 1.
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [5]:
#Array cuyos valores son todos el valor indicado como segundo parametro de la funcion

np.full((2, 3, 4), 8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [6]:
# el resultado de np.empty no es predecible 
# Inicializa los valores del array con lo que haya en memoria en ese momento 
np.empty((2, 3, 9))

array([[[ 6.67389309e-317,  0.00000000e+000,  1.03581153e+219,
          1.71011790e+214,  2.41578815e-311,  3.81291163e+180,
          3.55760877e+180,  1.26927730e-277,  1.57989218e-313],
        [ 1.31353237e-308,  1.03581152e+219,  9.78711731e+199,
          1.53446210e-253,  2.64089007e-313,  2.00886795e-308,
          3.38460675e+125,  6.96411095e+252,  9.24692396e+228],
        [-3.38460677e+125,  2.57153710e+151,  4.09487469e-308,
         -3.38460759e+125,  8.56555737e+218,  8.36407307e+149,
          6.68546367e+151,  1.14428844e+243,  2.08846826e-310]],

       [[ 3.42196482e-210,  1.68582619e-312,  1.08785252e-306,
          1.33360300e+241,  5.72811544e-310,  6.31241093e-191,
          2.78926400e-312,  3.53860623e-308,  1.33360302e+241],
        [ 8.00968531e-310,  2.24261886e-205,  4.12628713e-313,
          7.81668446e-305,  1.33360396e+241,  1.76252970e-310,
          6.04608850e-138,  5.54041819e+228,  6.75635367e-312],
        [ 2.03246818e-260,  1.45894756e-303,  8.

In [7]:
# Inicializacion del array utilizando un array de python
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Creacion del arrat utilizando una funcion basada en rangos.
# (minimo, maximo, número de elementos del array
print(np.linspace(0, 6, 10))

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [10]:
# Inicializar un array con valores aleatorios.
np.random.rand(2, 3, 4)

array([[[0.22737138, 0.62890454, 0.07310533, 0.43421841],
        [0.26229093, 0.71175157, 0.56811768, 0.41194581],
        [0.74641007, 0.170856  , 0.93947838, 0.18280026]],

       [[0.94174478, 0.29875515, 0.3919354 , 0.20000536],
        [0.51974213, 0.11514095, 0.63102739, 0.19431148],
        [0.58526865, 0.44746986, 0.24354366, 0.7112472 ]]])

In [11]:
# Inicializar un array con valores aleatorios conforme a una distribucion normal.
# randn 
np.random.randn(2, 4)

array([[-0.56620078, -0.84277681,  0.39068343, -1.59914094],
       [ 1.23653519,  0.04413195,  0.40813565, -0.82949408]])

%matplotlib inline
import matplotlib.pyplot as plt

c = np.random.randn(100000)

plt.hist(c, bins=400)

plt.show()

In [15]:
# Inicializar un array utilizando una funcion personalizada.
# la funcion finaliza con el enter
def function(x, y):
    return x + 2 * y

np.fromfunction(function, (3, 5))

array([[ 0.,  2.,  4.,  6.,  8.],
       [ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]])

## Acceso a los elementos de un array 
### Array unidimensional

In [16]:
# Creacion de un array unidimensional.

array_uni = np.array([1, 3, 5, 7, 9, 11])

print("Shape: ", array_uni.shape)

print("Array Uni: ", array_uni)

Shape:  (6,)
Array Uni:  [ 1  3  5  7  9 11]


In [17]:
# Accediendo al quinto elemento del array.
array_uni[4]

np.int64(9)

In [18]:
# Accediendo al tercer y cuarto elementos del array
array_uni[2:4]

array([5, 7])

In [23]:
# Acceder a los elementos 0,3,5 del array
array_uni[0::5]

array([ 1, 11])

## Array multidimensional 

In [25]:
# Creacion de un array multidimensional
array_multi = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Shape: ", array_multi.shape)

print("Array Multi: ", array_multi)

Shape:  (2, 4)
Array Multi:  [[1 2 3 4]
 [5 6 7 8]]


In [27]:
# Accediendo al cuarto elemento del array
array_multi[0, 3]

np.int64(4)

In [28]:
# Accediendo a la segunda fila del array
array_multi[1,:]

array([5, 6, 7, 8])

In [29]:
# Accediendo al tercer elemento  de las 2 primeras filas del array
array_multi[0: 2, 2]

array([3, 7])

## Modificacion de un array

In [31]:
# Creacion de un array unidimensional inicializado con el rango de elementos 0-27
array_uno = np.arange(28)
print("Shape: ", array_uno.shape)

print("Array: ", array_uno)

Shape:  (28,)
Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [33]:
# Cambiar las dimensiones del array y longitudes
array_uno.shape = (7,4)
print("Shape: ", array_uno.shape)

print("Array: \n", array_uno)

Shape:  (7, 4)
Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [34]:
# El ejemplo anterior devuelve un nuevo array que apunta a los mismos datos
# Nota: Las modificaciones en un array modifican el otro array 

array_dos = array_uno.reshape(4, 7)
print("Shape: ", array_dos.shape)

print("Array: \n", array_dos)

Shape:  (4, 7)
Array: 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [35]:
# Modificacion al array devuelto
array_dos[0,3] = 20
print("Array: \n", array_dos)

Array: 
 [[ 0  1  2 20  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [40]:
print("Array: \n", array_uno)

Array: 
 [[ 0  1  2 20]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [38]:
# Devolver el arreglo como estaba originalmente
# Nota: el  nuevo array apunta a los nuevos datos
print("Array: \n", array_uno.ravel())

Array: 
 [ 0  1  2 20  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


## Operaciones Aritmeticas con arrays

In [41]:
# Creacion de 2 arrays unidimencionales.

array_uno = np.arange(2, 18, 2)
array_dos = np.arange(8)

print("Array: \n", array_uno)
print("Array: \n", array_dos)

Array: 
 [ 2  4  6  8 10 12 14 16]
Array: 
 [0 1 2 3 4 5 6 7]


In [44]:
# suma
print(array_uno + array_dos)

[ 2  5  8 11 14 17 20 23]


In [45]:
# resta
print(array_uno - array_dos)

[2 3 4 5 6 7 8 9]


In [47]:
# multiplicacion
# Nota: no es una multiplicacion de matrices
print(array_uno * array_dos)

[  0   4  12  24  40  60  84 112]


## Broadcasting
Si se aplican operaciones aritmeticas sobre arrays que no tienen la misma forma (shape) numpy aplica una propiedad que se denomina Broadcasting.

In [49]:
# Creacion de 2 arrays unidimencionales
array_one = np.arange(5)
array_second = np.array([3])
print("Shape: ", array_one.shape)

print("Array: ", array_one)
print("////////////")
print("Shape: ", array_second.shape)

print("Array: ", array_second)

Shape:  (5,)
Array:  [0 1 2 3 4]
////////////
Shape:  (1,)
Array:  [3]


In [50]:
# sumas de ambos arrays
array_one + array_second

array([3, 4, 5, 6, 7])

In [51]:
# Creacion de 2 arrays multidimencionales y unidimencionales
array1 = np.arange(6)
array1.shape = (2,3)
array2 = np.arange(6,18,4)
print("Shape: ", array1.shape)

print("Array: \n", array1)
print("Shape: ", array2.shape)

print("Array: \n", array2)

Shape:  (2, 3)
Array: 
 [[0 1 2]
 [3 4 5]]
Shape:  (3,)
Array: 
 [ 6 10 14]


In [52]:
# suma de ambos arrays
array1 + array2

array([[ 6, 11, 16],
       [ 9, 14, 19]])

## Funciones, estadisticas sobre arrays

In [53]:
# Creacion de un array unidimensional
array1 = np.arange(1,20,2)
print("array 1:\n", array1)


array 1:
 [ 1  3  5  7  9 11 13 15 17 19]


In [54]:
# Media de los elementos dela array
array1.mean()

np.float64(10.0)

In [55]:
# Suma de los elementos del array
array1.sum()

np.int64(100)

funciones universales eficientes proporcionadas por numpy **unfuction**

In [56]:
# Cuadrado de los elementos del array
np.square(array1)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [57]:
# Raiz cuadrada de los elementos del array
np.sqrt(array1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [58]:
# Exponencial de los elementos del array.
np.exp(array1)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])

In [59]:
# Logaritmo natural de los elemento del array 
np.log(array1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])